theme = "default"
baseURL = ""
languageCode = "en-us"
title = "raspi@GitHub"
copyright = "Copyright (c) 2012-, Pekka Järvinen; All rights reserved."
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
  description    = "raspi@GitHub"
  withSitePosts  = true
  searchDomain   = ""
  noCategoryLink = true
  repositoryUrl  = "https://github.com/raspi"
  highlightStyle = "github"
  analytics = "UA-37317362-1"
  gverification = "c6r4YUg5mxq7D7PRfX2K-eUcAYv6Awu0F-cU3caM9dc"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name   = "Projects"
  url    = "/projects/"
  weight = 10